### PR TITLE
OCR

### PR DESCRIPTION
**Pull request by sebllll**
# PR Details

Adds a node for Optical Character Recognition

## Description

Image > OCR > text (and rectangles and confidences)

## Motivation and Context

i want to do ocr in vvvv

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My change requires a change to the documentation

### CODE REVIEW

**Comment by joreg** [comment]
great, thanks already!

two things: 
- please rename the help to: "HowTo Detect text using OCR" so it will be found when searching for "OCR". in the help.xml i'd also add an entry with tag "tesseract"
- the downloading of files and how/where to place them isn't really clear to me. currently there are 3 links to repos. could you instead link to the releases pages of those repos that has zip downloads. and mention which exact version you tested with, so we can replicate your setup exactly. then also show how to place files exactly. should they all be flat in the datapath? can i use only one of the 3 mentioned models at the same time? can i put those in subfolders next to each other and then switch between them?...

**Comment by sebllll** [comment]
allright. anything unclear from the updated helppatch?

**Comment by joreg** [comment]
very clear now. thanks.

but what's wrong with the built-in FileDownloader?

**Comment by sebllll** [comment]
i needed a fragmented version, so i put the outputs on a **Get** operation in order to set the rest on Create

**Comment by joreg** [comment]
can you elaborate on why you need a fragmented version? i just replaced it with the non-fragmented FileDownloader and got the same behavior... what am i missing?

**Comment by sebllll** [comment]
the way i set the downloader on create forced me to have the output also on create.

image
vs.
image

How would you do that with a non-fragmented version?

**Comment by joreg** [comment]
right, but why have the downloader on create at all?

**Comment by sebllll** [comment]
Many ways lead to Rome... please see the last iteration that is on Update and uses the original FileDownloader.

**Comment by joreg** [comment]
perfect. thanks! 
@ravazquez from my side all good. please merge as you see fit.

**Pull request merged**
